version: '3.4'

services:
  userapi.webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  WepApiSqldb:
    container_name: WepApiSqldb 
    ports:
      - "1433:1433" 
    environment:
      SA_PASSWORD: "Odb12345678"
      ACCEPT_EULA: "Y"